<script setup lang="ts">
import { computed, ref } from 'vue'
import { Head, router } from '@inertiajs/vue3'
import { AdminLayout } from '@/components/admin/layout'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useToast } from '@/composables/useToast'
import { ShieldCheck, ShieldAlert, Copy, KeyRound } from 'lucide-vue-next'

const props = defineProps<{
  panelPath: string
  mfa: {
    enabled: boolean
    confirmedAt: string | null
    hasPendingSetup: boolean
  }
  pendingSetup: {
    secret: string
    otpAuthUri: string
  } | null
  recoveryCodesCount: number
}>()

const toast = useToast()
const processing = ref(false)
const confirmCode = ref('')
const disableCode = ref('')
const disablePassword = ref('')
const regenerateCode = ref('')
const latestRecoveryCodes = ref<string[] | null>(null)
const pendingSetup = ref(props.pendingSetup)

const isEnabled = computed(() => props.mfa.enabled)
const hasPendingSetup = computed(() => Boolean(pendingSetup.value))

function refreshPage() {
  router.reload({ only: ['mfa', 'pendingSetup', 'recoveryCodesCount'] })
}

async function startSetup() {
  processing.value = true
  try {
    const res = await fetch(`${props.panelPath}/security/mfa/setup`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
      },
      body: JSON.stringify({}),
    })
    const payload = await res.json()
    if (!res.ok || !payload?.success) {
      throw new Error(payload?.message || 'Unable to start MFA setup')
    }
    pendingSetup.value = payload.pendingSetup
    latestRecoveryCodes.value = null
    toast.success('MFA setup ready', 'Enter a code from your authenticator app to confirm.')
  } catch (error: any) {
    toast.error('Error', error?.message || 'Unable to start MFA setup')
  } finally {
    processing.value = false
  }
}

async function confirmSetup() {
  if (!confirmCode.value.trim()) {
    toast.error('Code required', 'Enter the TOTP code generated by your app.')
    return
  }

  processing.value = true
  try {
    const res = await fetch(`${props.panelPath}/security/mfa/confirm`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
      },
      body: JSON.stringify({ code: confirmCode.value }),
    })
    const payload = await res.json()
    if (!res.ok || !payload?.success) {
      throw new Error(payload?.message || 'Unable to confirm MFA')
    }
    latestRecoveryCodes.value = payload.recoveryCodes || []
    confirmCode.value = ''
    pendingSetup.value = null
    toast.success('MFA enabled', 'Store your recovery codes in a safe place.')
    refreshPage()
  } catch (error: any) {
    toast.error('Error', error?.message || 'Unable to confirm MFA')
  } finally {
    processing.value = false
  }
}

async function disableMfa() {
  if (!disableCode.value.trim() && !disablePassword.value.trim()) {
    toast.error('Verification required', 'Enter an MFA code or your password.')
    return
  }

  processing.value = true
  try {
    const res = await fetch(`${props.panelPath}/security/mfa/disable`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
      },
      body: JSON.stringify({
        code: disableCode.value,
        password: disablePassword.value,
      }),
    })
    const payload = await res.json()
    if (!res.ok || !payload?.success) {
      throw new Error(payload?.message || 'Unable to disable MFA')
    }
    disableCode.value = ''
    disablePassword.value = ''
    latestRecoveryCodes.value = null
    toast.success('MFA disabled')
    refreshPage()
  } catch (error: any) {
    toast.error('Error', error?.message || 'Unable to disable MFA')
  } finally {
    processing.value = false
  }
}

async function regenerateRecoveryCodes() {
  if (!regenerateCode.value.trim()) {
    toast.error('Code required', 'Enter a valid MFA code.')
    return
  }

  processing.value = true
  try {
    const res = await fetch(`${props.panelPath}/security/mfa/recovery-codes`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Requested-With': 'XMLHttpRequest',
      },
      body: JSON.stringify({ code: regenerateCode.value }),
    })
    const payload = await res.json()
    if (!res.ok || !payload?.success) {
      throw new Error(payload?.message || 'Unable to regenerate codes')
    }
    latestRecoveryCodes.value = payload.recoveryCodes || []
    regenerateCode.value = ''
    toast.success('Codes regenerated', 'Store these new codes right away.')
    refreshPage()
  } catch (error: any) {
    toast.error('Error', error?.message || 'Unable to regenerate codes')
  } finally {
    processing.value = false
  }
}

async function copy(value: string) {
  try {
    await navigator.clipboard.writeText(value)
    toast.success('Copied')
  } catch {
    toast.error('Unable to copy to clipboard')
  }
}
</script>

<template>
  <Head title="MFA Security" />

  <AdminLayout>
    <div class="space-y-6 max-w-4xl">
      <div class="flex items-center gap-3">
        <div
          class="flex h-10 w-10 items-center justify-center rounded-xl"
          :class="
            isEnabled ? 'bg-emerald-500/10 text-emerald-600' : 'bg-amber-500/10 text-amber-600'
          "
        >
          <ShieldCheck v-if="isEnabled" class="h-5 w-5" />
          <ShieldAlert v-else class="h-5 w-5" />
        </div>
        <div>
          <h1 class="text-2xl font-bold tracking-tight">Multi-factor authentication</h1>
          <p class="text-muted-foreground">
            Strengthen panel access with a TOTP code and recovery codes.
          </p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>MFA status</CardTitle>
          <CardDescription v-if="isEnabled"> MFA is enabled on your account. </CardDescription>
          <CardDescription v-else>
            MFA is disabled. Enable it to secure panel access.
          </CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <div v-if="!isEnabled && !hasPendingSetup" class="flex items-center gap-3">
            <Button :disabled="processing" @click="startSetup"> Enable MFA </Button>
          </div>

          <div v-if="hasPendingSetup" class="space-y-4 rounded-lg border p-4">
            <div class="space-y-1">
              <Label>Manual secret</Label>
              <div class="flex items-center gap-2">
                <Input :model-value="pendingSetup?.secret || ''" readonly />
                <Button variant="outline" size="icon" @click="copy(pendingSetup?.secret || '')">
                  <Copy class="h-4 w-4" />
                </Button>
              </div>
            </div>

            <div class="space-y-1">
              <Label>URI otpauth</Label>
              <div class="flex items-center gap-2">
                <Input :model-value="pendingSetup?.otpAuthUri || ''" readonly />
                <Button variant="outline" size="icon" @click="copy(pendingSetup?.otpAuthUri || '')">
                  <Copy class="h-4 w-4" />
                </Button>
              </div>
            </div>

            <div class="space-y-2">
              <Label for="confirm-code">Confirmation code</Label>
              <div class="flex items-center gap-2">
                <Input id="confirm-code" v-model="confirmCode" placeholder="123456" />
                <Button :disabled="processing" @click="confirmSetup">Confirm</Button>
              </div>
            </div>
          </div>

          <div v-if="isEnabled" class="space-y-4">
            <div class="text-sm text-muted-foreground">
              Recovery codes available: {{ recoveryCodesCount }}
            </div>

            <div class="space-y-2 rounded-lg border p-4">
              <div class="flex items-center gap-2 font-medium">
                <KeyRound class="h-4 w-4" />
                Regenerate recovery codes
              </div>
              <div class="flex items-center gap-2">
                <Input v-model="regenerateCode" placeholder="Current MFA code" />
                <Button variant="outline" :disabled="processing" @click="regenerateRecoveryCodes">
                  Regenerate
                </Button>
              </div>
            </div>

            <div class="space-y-2 rounded-lg border border-destructive/30 p-4">
              <div class="font-medium text-destructive">Disable MFA</div>
              <p class="text-sm text-muted-foreground">
                Enter an MFA code or your password to confirm.
              </p>
              <Input v-model="disableCode" placeholder="MFA code (optional)" />
              <Input v-model="disablePassword" type="password" placeholder="Password (optional)" />
              <Button variant="destructive" :disabled="processing" @click="disableMfa">
                Disable
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card v-if="latestRecoveryCodes && latestRecoveryCodes.length > 0">
        <CardHeader>
          <CardTitle>Recovery codes</CardTitle>
          <CardDescription>
            These codes are shown only once. Store them immediately.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div class="grid gap-2 sm:grid-cols-2">
            <div
              v-for="code in latestRecoveryCodes"
              :key="code"
              class="rounded border bg-muted/40 px-3 py-2 font-mono text-sm"
            >
              {{ code }}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  </AdminLayout>
</template>
